### PR TITLE
 This is a possible solution for the restructuring of our LESS files

### PR DESCRIPTION
**Pull request by k33**
See #74.

### CODE REVIEW

**Comment by willmcl** [comment]
Great, Where will layout.less stuff go? style.less?

**Comment by k33** [comment]
Yes I saw layout becoming part of our base styles. No project has had more than a hand full of layout styles. 

Or perhaps we could keep layout but include our grid styles in there?

**Comment by willmcl** [comment]
Yep, I agree. Perhaps we will need to separate our style.less into individual files too? ie. a new folder called 'base' with base/fonts.less, base/typography.less, base/layout.less, base/variables.less etc. etc.

**Comment by k33** [comment]
Ok cool I will have a look at further separation as it sounds good. Just need to make sure it is not to complex.

**Pull request merged**
